# -*- coding: utf-8 -*-
"""Copy_Email_app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IevGtOgBeEPL-_jEYoAtQrBEbmoUBi8O
"""

import streamlit as st
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split

# Load dataset
df = pd.read_csv('/content/mail_data.csv')

# Convert labels
df.loc[df['Category'] == 'spam', 'Category'] = 0
df.loc[df['Category'] == 'ham', 'Category'] = 1

X = df['Message']
y = df['Category'].astype('int')

# Split data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Feature extraction
vectorizer = TfidfVectorizer(min_df=1, stop_words='english', lowercase=True)
X_train_features = vectorizer.fit_transform(X_train)

# Train model
model = LogisticRegression()
model.fit(X_train_features, y_train)

# Streamlit UI
st.set_page_config(page_title="Spam Detector", page_icon="📧", layout="centered")

# Background styling
page_bg = """
<style>
[data-testid="stAppViewContainer"] {
    background-image: linear-gradient(to right top, #6a11cb, #2575fc);
    background-size: cover;
}
[data-testid="stHeader"] {
    background: rgba(0,0,0,0);
}
</style>
"""
st.markdown(page_bg, unsafe_allow_html=True)

st.title("📧 Spam Email Detector")
st.write("Enter an email / message below to check if it is **Spam** or **Ham**.")

# Input box
user_input = st.text_area("✍️ Paste your email/message here:")

if st.button("🔍 Detect"):
    if user_input.strip() != "":
        # Transform input
        input_features = vectorizer.transform([user_input])
        prediction = model.predict(input_features)[0]

        if prediction == 1:
            st.success("✅ This Email is **HAM (Not Spam)**")
        else:
            st.error("🚨 This Email is **SPAM**")
    else:
        st.warning("⚠️ Please enter some text first!")

